[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[window]
padding = { x = 4, y = 4 }
dynamic_padding = true
opacity = 0.9

[cursor]
style = {shape = "Beam"}
thickness = 0.4

[colors.primary]
background = "#111111"
